### ISSUE TITLE
Polymorphism and binding

### ISSUE THREAD

**Issue by jamescheney** [jstolarek/inferno#16]
Consider the following examples:
```
(*poly_binding_1*)
  let (x : ∀ a.((∀ b.  b → b) → int)) = λ(y:∀ b.  b → b). 42 in
  let (z : ∀ a.  a → a) =  λw. w in
  x (~z)
(*poly_binding_2*)
  let (x :(∀ a.  a → a) = λ(y:a). y in
  x 42
```
The first involves an ascribed polymorphic type with a variable `a` that is not used in the type (or in the body).
The second involves an ascribed polymorphic type whose variable is used in a type ascribed in a lambda.

Currently (4e19f88) both examples fail with an implementation bug.

**Comment by jstolarek** [comment]
Failure in `poly_binding_1` is yet another instance of #9, except that the presence of a bogus (unused) quantifier prevents the solution from working. Even worse, if I ignore the unused quantifiers and apply solution to the body it's still wrong, because then I have to restore these quantifiers and end up in a situation where the body of quantified scheme consists of non-generic variables, which is wrong. The only right thing to do here is removing variables from the pool. This is something I wanted to avoid due to its computational complexity, but this is the right thing to do. So in order to improve performance I'm applying a solution conditionally, i.e. only remove variables from the pool when a type has only unused quantifiers. See 2d56218

**Comment by jstolarek** [comment]
`poly_binding_2` doesn't work for an obvious reason: in an annotated let bidning ∀ doesn't bring quantifiers into scope in a let-bound term. So the type annotation on `y` is invalid since `a` is an unbound variable. I believe that the solver is actually prepared to handle this and the problem lies on the client side. Recall that types in inferno are represented using unification variables and client-defined type structure interleaved with each other (variables contain structure, structure contains variables). Annotations are converted into a structure that is then placed inside a fresh variable - this happens in SolverHi. However, if an annotation is just a variable, like in the case of `λ(y:a). ...`, there is no way to construct a structure. Hence an assertion failure that causes test failure - there's really no code that could be placed there. I think the way to solve this is to have signatures converted directly to variables. Initial work is on `scoped_tyvars` branch.

**Comment by jstolarek** [comment]
Going back to `poly_binding_1`:

> The only right thing to do here is removing variables from the pool. This is something I wanted to avoid due to its computational complexity, but this is the right thing to do. So in order to improve performance I'm applying a solution conditionally, i.e. only remove variables from the pool when a type has only unused quantifiers.

That conditional approach doesn't work.  Consider new example `poly_binding_3`:

```
let (x : ∀ a. (∀ b. a → b) → Int) = λ(z : (∀ b. a → b)). 1 in 1
```
Here `a` is not an unused quantifier and will prevent removal of variable representing `Int` from the pool. The solution is to first bind any unbound generic variables and any leftover unbound variables in the body are removed from the pool. (Potential bug: we might also want to look deeper into the type, not just at the top level, but I couldn't construct an example that would trigger the problem).

I also fixed `poly_binding_2` - some code got simplified but there's also a fair deal of hackery. I need to document these hacks before merging with master.
